import { IMapField } from "homam/modules/field/interfaces";
import {desertField, goldResourceField, grassField, mountainField, woodResourceField} from "homam/modules/field/utils";

export const initMapFields: IMapField[][] = [
  [
    { field: desertField },
    {field: mountainField },
    {field: mountainField },
    {field: grassField, onField: goldResourceField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: desertField },
    {field: desertField },
    {field: desertField },
  ],
  [
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: mountainField },
    {field: mountainField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: desertField },
    {field: desertField },
    {field: desertField },
  ],
  [
    {field: mountainField },
    {field: mountainField },
    {field: grassField },
    {field: mountainField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: mountainField },
    {field: mountainField },
    {field: mountainField },
  ],
  [
    {field: mountainField },
    {field: grassField },
    {field: grassField },
    {field: mountainField },
    {field: grassField },
    {field: mountainField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: mountainField },
    {field: mountainField },
    {field: mountainField },
  ],
  [
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: mountainField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: mountainField },
    {field: mountainField },
    {field: mountainField },
  ],
  [
    {field: mountainField },
    {field: mountainField },
    {field: grassField },
    {field: grassField },
    {field: mountainField },
    {field: mountainField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: mountainField },
    {field: mountainField },
    {field: mountainField },
  ],
  [
    {field: mountainField },
    {field: mountainField },
    {field: grassField },
    {field: grassField },
    {field: mountainField },
    {field: mountainField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: desertField },
    {field: desertField },
    {field: grassField },
  ],
  [
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: desertField },
    {field: grassField, onField: woodResourceField },
    {field: grassField },
  ],
  [
    {field: mountainField },
    {field: mountainField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: desertField },
    {field: desertField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
  ],
  [
    {field: mountainField },
    {field: mountainField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: desertField },
    {field: desertField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
  ],
  [
    {field: mountainField },
    {field: mountainField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
  ],
  [
    {field: mountainField },
    {field: mountainField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
    {field: grassField },
  ],
];
