import { IMapField } from "homam/modules/field/interfaces";
import {desertField, grassField, mountainField} from "homam/modules/field/utils";

export const initMapFields: IMapField[][] = [
  [
    { type: desertField },
    {type: mountainField },
    {type: mountainField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: desertField },
    {type: desertField },
    {type: desertField },
  ],
  [
    {type: grassField },
    {type: grassField},
    {type: grassField },
    {type: mountainField },
    {type: mountainField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: desertField },
    {type: desertField },
    {type: desertField },
  ],
  [
    {type: mountainField },
    {type: mountainField },
    {type: grassField },
    {type: mountainField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: mountainField },
    {type: mountainField },
    {type: mountainField },
  ],
  [
    {type: mountainField },
    {type: grassField },
    {type: grassField },
    {type: mountainField },
    {type: grassField },
    {type: mountainField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: mountainField },
    {type: mountainField },
    {type: mountainField },
  ],
  [
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: mountainField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: mountainField },
    {type: mountainField },
    {type: mountainField },
  ],
  [
    {type: mountainField },
    {type: mountainField },
    {type: grassField },
    {type: grassField },
    {type: mountainField },
    {type: mountainField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: mountainField },
    {type: mountainField },
    {type: mountainField },
  ],
  [
    {type: mountainField },
    {type: mountainField },
    {type: grassField },
    {type: grassField },
    {type: mountainField },
    {type: mountainField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: desertField },
    {type: desertField },
    {type: grassField },
  ],
  [
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: desertField },
    {type: grassField },
    {type: grassField },
  ],
  [
    {type: mountainField },
    {type: mountainField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: desertField },
    {type: desertField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
  ],
  [
    {type: mountainField },
    {type: mountainField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: desertField },
    {type: desertField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
  ],
  [
    {type: mountainField },
    {type: mountainField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
  ],
  [
    {type: mountainField },
    {type: mountainField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
    {type: grassField },
  ],
];
